module.exports = {
    DATA_NOT_VALID: 'DATA_NOT_VALID',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    SERVICE_NOT_AVAILABLE: 'SERVICE_NOT_AVAILABLE',
    DATABASE_ERROR: 'DATABASE_ERROR'
}
